name: "Coding Standards"

on:
  pull_request:
    branches:
      - master

jobs:
  coding-standards:
    name: "Linting"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: npm ci

      - name: Lint
        run: npm run lint
